// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: lexer/CLexerSpec.flex

package lexer;

import model.Token;
import model.OperatorToken;
import model.KeywordToken;
import model.LiteralToken;
import model.IdentifierToken;

import validation.TokenError;
import validation.IllegalTokenException;

import java.util.ArrayList;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class CLexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\2\10\1\6\1\11\1\12\2\13\1\14"+
    "\1\15\1\13\1\16\1\13\1\17\1\20\11\21\2\13"+
    "\1\22\1\23\1\24\1\13\1\10\6\25\21\26\1\27"+
    "\2\26\1\13\1\30\1\13\1\31\1\26\1\0\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\26\1\43\1\44\1\45\1\46\1\47\1\50\1\26"+
    "\1\51\1\52\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\61\1\13\1\62\2\13\6\0\1\3\u01a2\0\2\3"+
    "\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\1\3\1\1\4\3"+
    "\2\5\2\3\20\6\1\3\1\7\1\10\1\11\4\0"+
    "\1\2\2\5\6\6\1\12\4\6\1\12\13\6\1\13"+
    "\1\14\1\15\1\16\1\5\2\0\2\5\30\6\1\0"+
    "\1\2\27\6";

  private static int [] zzUnpackAction() {
    int [] result = new int[125];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\146\0\231\0\314\0\377\0\u0132"+
    "\0\u0165\0\146\0\u0198\0\u01cb\0\u01fe\0\u0231\0\u0264\0\u0297"+
    "\0\u02ca\0\u02fd\0\u0330\0\u0363\0\u0396\0\u03c9\0\u03fc\0\u042f"+
    "\0\u0462\0\u0495\0\u04c8\0\u04fb\0\u052e\0\u0561\0\u0594\0\u05c7"+
    "\0\u05fa\0\u062d\0\u0660\0\146\0\u0693\0\u06c6\0\u06f9\0\u072c"+
    "\0\u075f\0\u0792\0\u07c5\0\u07f8\0\u082b\0\u085e\0\u0891\0\u08c4"+
    "\0\u08f7\0\u092a\0\u095d\0\u0990\0\u09c3\0\u09f6\0\u0a29\0\u02fd"+
    "\0\u0a5c\0\u0a8f\0\u0ac2\0\u0af5\0\u0b28\0\u0b5b\0\u0b8e\0\u0bc1"+
    "\0\u0bf4\0\u0c27\0\u0c5a\0\146\0\146\0\146\0\146\0\146"+
    "\0\u0c8d\0\u0cc0\0\u0cf3\0\u0d26\0\u0d59\0\u0d8c\0\u0dbf\0\u0df2"+
    "\0\u0e25\0\u0e58\0\u0e8b\0\u0ebe\0\u0ef1\0\u0f24\0\u0f57\0\u0f8a"+
    "\0\u0fbd\0\u0ff0\0\u1023\0\u1056\0\u1089\0\u10bc\0\u10ef\0\u1122"+
    "\0\u1155\0\u1188\0\u11bb\0\u11ee\0\u1221\0\u0c8d\0\u1254\0\u1287"+
    "\0\u12ba\0\u12ed\0\u1320\0\u1353\0\u1386\0\u13b9\0\u13ec\0\u141f"+
    "\0\u1452\0\u1485\0\u14b8\0\u14eb\0\u151e\0\u1551\0\u1584\0\u15b7"+
    "\0\u15ea\0\u161d\0\u1650\0\u1683\0\u16b6";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[125];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\3\1\4\1\5\1\6\1\7\1\3"+
    "\1\10\1\11\1\12\1\6\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\6\1\21\3\22\1\3\1\6\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\22\1\32"+
    "\1\22\1\33\4\22\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\3\22\1\42\2\43\1\3\2\43\1\3\1\43"+
    "\1\44\20\43\1\45\32\43\65\0\1\4\103\0\1\12"+
    "\37\0\14\46\1\0\46\46\11\0\1\12\11\0\1\12"+
    "\45\0\1\47\1\0\2\47\6\0\2\47\3\0\3\47"+
    "\1\50\1\0\30\47\16\0\1\12\5\0\1\12\55\0"+
    "\1\12\4\0\2\12\52\0\1\51\2\0\1\52\3\0"+
    "\1\12\37\0\2\53\4\0\21\53\1\54\27\53\1\54"+
    "\2\53\1\54\2\53\4\0\12\53\2\17\41\53\22\0"+
    "\1\6\1\12\62\0\1\12\1\6\56\0\2\22\3\0"+
    "\3\22\2\0\30\22\21\0\2\22\3\0\3\22\2\0"+
    "\22\22\1\55\5\22\21\0\2\22\3\0\3\22\2\0"+
    "\17\22\1\56\10\22\21\0\2\22\3\0\3\22\2\0"+
    "\1\57\6\22\1\60\5\22\1\61\12\22\21\0\2\22"+
    "\3\0\3\22\2\0\4\22\1\62\10\22\1\63\12\22"+
    "\21\0\2\22\3\0\3\22\2\0\12\22\1\57\1\22"+
    "\1\64\10\22\1\65\2\22\21\0\2\22\3\0\3\22"+
    "\2\0\12\22\1\66\2\22\1\67\12\22\21\0\2\22"+
    "\3\0\3\22\2\0\15\22\1\55\12\22\21\0\2\22"+
    "\3\0\3\22\2\0\5\22\1\70\6\22\1\71\13\22"+
    "\21\0\2\22\3\0\3\22\2\0\15\22\1\72\12\22"+
    "\21\0\2\22\3\0\3\22\2\0\4\22\1\73\23\22"+
    "\21\0\2\22\3\0\3\22\2\0\7\22\1\74\1\75"+
    "\10\22\1\76\2\22\1\77\3\22\21\0\2\22\3\0"+
    "\3\22\2\0\26\22\1\100\1\22\21\0\2\22\3\0"+
    "\3\22\2\0\14\22\1\101\13\22\21\0\2\22\3\0"+
    "\3\22\2\0\15\22\1\102\12\22\21\0\2\22\3\0"+
    "\3\22\2\0\7\22\1\103\20\22\24\0\1\12\36\0"+
    "\1\12\2\43\1\0\2\43\1\0\1\43\1\0\20\43"+
    "\1\0\32\43\7\0\1\104\36\0\1\105\2\0\1\106"+
    "\1\0\1\107\16\0\1\110\65\0\1\110\103\0\1\47"+
    "\12\0\1\47\2\0\1\47\1\0\1\47\6\0\1\47"+
    "\14\111\1\112\46\111\2\52\1\4\2\52\1\5\55\52"+
    "\20\0\2\53\61\0\2\54\3\0\1\113\4\0\6\114"+
    "\43\0\2\22\3\0\3\22\2\0\21\22\1\115\6\22"+
    "\21\0\2\22\3\0\3\22\2\0\4\22\1\116\23\22"+
    "\21\0\2\22\3\0\3\22\2\0\20\22\1\117\7\22"+
    "\21\0\2\22\3\0\3\22\2\0\1\67\27\22\21\0"+
    "\2\22\3\0\3\22\2\0\14\22\1\120\13\22\21\0"+
    "\2\22\3\0\3\22\2\0\5\22\1\121\22\22\21\0"+
    "\2\22\3\0\3\22\2\0\22\22\1\122\5\22\21\0"+
    "\2\22\3\0\3\22\2\0\22\22\1\123\5\22\21\0"+
    "\2\22\3\0\3\22\2\0\21\22\1\124\6\22\21\0"+
    "\2\22\3\0\3\22\2\0\15\22\1\125\12\22\21\0"+
    "\2\22\3\0\3\22\2\0\17\22\1\70\10\22\21\0"+
    "\2\22\3\0\3\22\2\0\21\22\1\70\6\22\21\0"+
    "\2\22\3\0\3\22\2\0\14\22\1\126\13\22\21\0"+
    "\2\22\3\0\3\22\2\0\6\22\1\127\12\22\1\130"+
    "\6\22\21\0\2\22\3\0\3\22\2\0\15\22\1\131"+
    "\12\22\21\0\2\22\3\0\3\22\2\0\6\22\1\132"+
    "\20\22\1\133\21\0\2\22\3\0\3\22\2\0\1\134"+
    "\16\22\1\135\10\22\21\0\2\22\3\0\3\22\2\0"+
    "\10\22\1\136\17\22\21\0\2\22\3\0\3\22\2\0"+
    "\16\22\1\137\11\22\21\0\2\22\3\0\3\22\2\0"+
    "\10\22\1\140\7\22\1\141\7\22\21\0\2\22\3\0"+
    "\3\22\2\0\10\22\1\142\1\22\1\143\15\22\21\0"+
    "\2\22\3\0\3\22\2\0\10\22\1\144\17\22\1\0"+
    "\14\111\1\145\62\111\1\145\2\111\1\146\43\111\20\0"+
    "\2\113\3\0\1\113\55\0\2\114\10\0\6\114\43\0"+
    "\2\22\3\0\3\22\2\0\15\22\1\70\12\22\21\0"+
    "\2\22\3\0\3\22\2\0\1\147\27\22\21\0\2\22"+
    "\3\0\3\22\2\0\4\22\1\70\23\22\21\0\2\22"+
    "\3\0\3\22\2\0\20\22\1\71\1\150\6\22\21\0"+
    "\2\22\3\0\3\22\2\0\1\151\27\22\21\0\2\22"+
    "\3\0\3\22\2\0\1\22\1\144\26\22\21\0\2\22"+
    "\3\0\3\22\2\0\13\22\1\70\14\22\21\0\2\22"+
    "\3\0\3\22\2\0\4\22\1\152\23\22\21\0\2\22"+
    "\3\0\3\22\2\0\1\71\27\22\21\0\2\22\3\0"+
    "\3\22\2\0\6\22\1\70\21\22\21\0\2\22\3\0"+
    "\3\22\2\0\10\22\1\153\17\22\21\0\2\22\3\0"+
    "\3\22\2\0\22\22\1\152\5\22\21\0\2\22\3\0"+
    "\3\22\2\0\17\22\1\71\10\22\21\0\2\22\3\0"+
    "\3\22\2\0\14\22\1\154\13\22\21\0\2\22\3\0"+
    "\3\22\2\0\4\22\1\155\23\22\21\0\2\22\3\0"+
    "\3\22\2\0\21\22\1\156\6\22\21\0\2\22\3\0"+
    "\3\22\2\0\22\22\1\157\5\22\21\0\2\22\3\0"+
    "\3\22\2\0\21\22\1\160\6\22\21\0\2\22\3\0"+
    "\3\22\2\0\4\22\1\161\23\22\21\0\2\22\3\0"+
    "\3\22\2\0\15\22\1\162\12\22\21\0\2\22\3\0"+
    "\3\22\2\0\10\22\1\163\17\22\21\0\2\22\3\0"+
    "\3\22\2\0\3\22\1\70\24\22\21\0\2\22\3\0"+
    "\3\22\2\0\1\164\27\22\21\0\2\22\3\0\3\22"+
    "\2\0\12\22\1\117\15\22\1\0\14\111\1\145\2\111"+
    "\1\4\43\111\20\0\2\22\3\0\3\22\2\0\11\22"+
    "\1\70\16\22\21\0\2\22\3\0\3\22\2\0\10\22"+
    "\1\165\17\22\21\0\2\22\3\0\3\22\2\0\22\22"+
    "\1\166\5\22\21\0\2\22\3\0\3\22\2\0\17\22"+
    "\1\162\10\22\21\0\2\22\3\0\3\22\2\0\20\22"+
    "\1\167\7\22\21\0\2\22\3\0\3\22\2\0\4\22"+
    "\1\142\23\22\21\0\2\22\3\0\3\22\2\0\15\22"+
    "\1\170\12\22\21\0\2\22\3\0\3\22\2\0\10\22"+
    "\1\171\17\22\21\0\2\22\3\0\3\22\2\0\2\22"+
    "\1\71\25\22\21\0\2\22\3\0\3\22\2\0\2\22"+
    "\1\172\25\22\21\0\2\22\3\0\3\22\2\0\3\22"+
    "\1\173\24\22\21\0\2\22\3\0\3\22\2\0\14\22"+
    "\1\70\13\22\21\0\2\22\3\0\3\22\2\0\6\22"+
    "\1\132\21\22\21\0\2\22\3\0\3\22\2\0\21\22"+
    "\1\103\6\22\21\0\2\22\3\0\3\22\2\0\14\22"+
    "\1\174\13\22\21\0\2\22\3\0\3\22\2\0\12\22"+
    "\1\71\15\22\21\0\2\22\3\0\3\22\2\0\21\22"+
    "\1\175\6\22\21\0\2\22\3\0\3\22\2\0\5\22"+
    "\1\70\22\22\21\0\2\22\3\0\3\22\2\0\2\22"+
    "\1\70\25\22\21\0\2\22\3\0\3\22\2\0\7\22"+
    "\1\70\20\22\21\0\2\22\3\0\3\22\2\0\4\22"+
    "\1\170\23\22\21\0\2\22\3\0\3\22\2\0\22\22"+
    "\1\117\5\22\21\0\2\22\3\0\3\22\2\0\4\22"+
    "\1\67\23\22\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5865];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\5\1\1\11\31\1\1\11\1\1\4\0"+
    "\32\1\5\11\2\0\32\1\1\0\30\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[125];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
	// string generation with STRING state
	private StringBuffer stringBuilder = new StringBuffer();

	// error lists
	ArrayList<TokenError> errorList = new ArrayList<>();

	public ArrayList<TokenError> getErrorList() {
		ArrayList<TokenError> errorsList = (ArrayList<TokenError>) this.errorList.clone();
		this.errorList.clear();
		return errorsList;
	}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public CLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) throws IllegalTokenException {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new IllegalTokenException(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  throws IllegalTokenException {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException, IllegalTokenException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { this.errorList.add(new TokenError(yyline, yycolumn, yytext()));
	throw new IllegalTokenException("Illegal character <" + yytext() + ">" + "[Line:" + yyline + ",Column:" + yycolumn + "]");
            }
            // fall through
          case 15: break;
          case 2:
            { /* do nothing */
            }
            // fall through
          case 16: break;
          case 3:
            { return new OperatorToken(yyline, yycolumn, yytext());
            }
            // fall through
          case 17: break;
          case 4:
            { stringBuilder.setLength(0); yybegin(STRING);
            }
            // fall through
          case 18: break;
          case 5:
            { return new LiteralToken(yyline, yycolumn, yytext());
            }
            // fall through
          case 19: break;
          case 6:
            { return new IdentifierToken(yyline, yycolumn, yytext());
            }
            // fall through
          case 20: break;
          case 7:
            { stringBuilder.append( yytext() );
            }
            // fall through
          case 21: break;
          case 8:
            { yybegin(YYINITIAL);
		return new LiteralToken(yyline, yycolumn, stringBuilder.toString());
            }
            // fall through
          case 22: break;
          case 9:
            { stringBuilder.append('\\');
            }
            // fall through
          case 23: break;
          case 10:
            { return new KeywordToken(yyline, yycolumn, yytext());
            }
            // fall through
          case 24: break;
          case 11:
            { stringBuilder.append('\"');
            }
            // fall through
          case 25: break;
          case 12:
            { stringBuilder.append('\n');
            }
            // fall through
          case 26: break;
          case 13:
            { stringBuilder.append('\r');
            }
            // fall through
          case 27: break;
          case 14:
            { stringBuilder.append('\t');
            }
            // fall through
          case 28: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
