// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: lexer/CLexerSpec.flex

package lexer;

import model.Token;
import model.OperatorToken;
import model.KeywordToken;
import model.LiteralToken;
import model.IdentifierToken;

import validation.TokenError;
import validation.IllegalTokenException;

import java.util.ArrayList;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class CLexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\1\10\1\0\1\6\1\11\1\12\2\13"+
    "\1\14\1\15\1\13\1\16\1\17\1\20\1\21\7\22"+
    "\2\23\2\13\1\24\1\25\1\26\1\13\1\0\4\27"+
    "\1\30\1\27\21\31\1\32\2\31\1\13\1\33\1\13"+
    "\1\6\1\34\1\0\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\1\51"+
    "\1\52\1\53\1\54\1\46\1\55\1\56\1\57\1\60"+
    "\1\61\1\62\1\63\1\64\1\65\1\13\1\66\2\13"+
    "\6\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\1\3\1\1\5\3"+
    "\2\5\2\3\20\6\1\3\1\7\1\10\1\11\6\0"+
    "\1\5\1\0\1\2\1\0\2\5\1\12\2\13\1\0"+
    "\2\5\1\14\6\6\1\15\4\6\1\15\13\6\1\16"+
    "\1\17\1\20\1\21\1\5\5\0\2\5\1\12\1\13"+
    "\1\12\1\13\2\5\1\22\1\5\1\22\2\5\1\22"+
    "\1\5\1\22\2\5\1\14\30\6\3\0\1\2\1\0"+
    "\2\13\4\5\1\13\1\14\16\6\1\0\2\5\11\6";

  private static int [] zzUnpackAction() {
    int [] result = new int[172];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\156\0\245\0\334\0\u0113\0\u014a"+
    "\0\u0181\0\156\0\u01b8\0\u01ef\0\u0226\0\u025d\0\u0294\0\u02cb"+
    "\0\u0302\0\u0339\0\u0370\0\u03a7\0\u03de\0\u0415\0\u044c\0\u0483"+
    "\0\u04ba\0\u04f1\0\u0528\0\u055f\0\u0596\0\u05cd\0\u0604\0\u063b"+
    "\0\u0672\0\u06a9\0\u06e0\0\u0717\0\156\0\u074e\0\u0785\0\u07bc"+
    "\0\u07f3\0\u0226\0\u082a\0\u0861\0\u0226\0\u0898\0\u08cf\0\u0906"+
    "\0\u093d\0\u0974\0\u09ab\0\u09e2\0\u0a19\0\u0a50\0\u0a87\0\u0abe"+
    "\0\u0af5\0\u0b2c\0\u0b63\0\u0b9a\0\u0bd1\0\u0c08\0\u0c3f\0\u0c76"+
    "\0\u0cad\0\u0ce4\0\u0d1b\0\u0d52\0\u0370\0\u0d89\0\u0dc0\0\u0df7"+
    "\0\u0e2e\0\u0e65\0\u0e9c\0\u0ed3\0\u0f0a\0\u0f41\0\u0f78\0\u0faf"+
    "\0\156\0\156\0\156\0\156\0\156\0\u0fe6\0\u101d\0\u1054"+
    "\0\u108b\0\u10c2\0\u10f9\0\u1130\0\u1167\0\u119e\0\u11d5\0\u120c"+
    "\0\u1243\0\u127a\0\u12b1\0\u12e8\0\u131f\0\u1356\0\u138d\0\u13c4"+
    "\0\u13fb\0\u1432\0\u1469\0\u14a0\0\u14d7\0\u150e\0\u1545\0\u157c"+
    "\0\u15b3\0\u15ea\0\u1621\0\u1658\0\u168f\0\u16c6\0\u16fd\0\u1734"+
    "\0\u176b\0\u17a2\0\u17d9\0\u1810\0\u1847\0\u187e\0\u18b5\0\u18ec"+
    "\0\u1923\0\u195a\0\u1991\0\u19c8\0\u19ff\0\u1a36\0\u1a6d\0\u1aa4"+
    "\0\u1054\0\u1adb\0\u1b12\0\u1b49\0\u1b80\0\u1bb7\0\u1bee\0\u1c25"+
    "\0\u1c5c\0\u1c93\0\u1cca\0\u1d01\0\u1d38\0\u1d6f\0\u1da6\0\u1ddd"+
    "\0\u1e14\0\u1e4b\0\u1e82\0\u1eb9\0\u1ef0\0\u1f27\0\u1f5e\0\u1f95"+
    "\0\u1fcc\0\u2003\0\u203a\0\u2071\0\u20a8\0\u20df\0\u2116\0\u214d"+
    "\0\u2184\0\u21bb\0\u21f2\0\u2229";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[172];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\3\1\4\1\5\1\6\1\7\1\3"+
    "\1\10\1\11\1\12\1\6\1\13\1\14\1\15\1\16"+
    "\1\17\2\20\1\21\1\6\1\22\4\23\1\3\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\23"+
    "\1\33\2\23\1\34\4\23\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\3\23\1\43\2\44\1\3\2\44\1\3"+
    "\1\44\1\45\23\44\1\46\33\44\71\0\1\4\111\0"+
    "\1\12\41\0\14\47\1\0\52\47\11\0\1\12\13\0"+
    "\1\12\47\0\25\50\1\51\33\50\15\0\1\12\1\0"+
    "\1\52\1\0\1\53\2\54\1\0\1\12\57\0\1\12"+
    "\1\52\1\0\1\53\2\54\1\0\2\12\61\0\3\55"+
    "\57\0\1\56\3\0\1\57\4\0\1\12\41\0\2\60"+
    "\4\0\11\60\1\61\1\60\2\62\1\63\3\60\3\64"+
    "\1\65\1\60\27\64\1\65\2\64\1\66\2\60\4\0"+
    "\11\60\1\61\1\60\1\67\2\70\3\60\4\71\1\60"+
    "\1\64\31\71\1\60\24\0\1\6\1\12\66\0\1\12"+
    "\1\6\61\0\3\23\3\0\4\23\1\0\32\23\22\0"+
    "\3\23\3\0\4\23\1\0\24\23\1\72\5\23\22\0"+
    "\3\23\3\0\4\23\1\0\21\23\1\73\10\23\22\0"+
    "\3\23\3\0\4\23\1\0\1\23\1\74\6\23\1\75"+
    "\6\23\1\76\12\23\22\0\3\23\3\0\4\23\1\0"+
    "\5\23\1\77\11\23\1\100\12\23\22\0\3\23\3\0"+
    "\4\23\1\0\14\23\1\74\1\23\1\101\10\23\1\102"+
    "\2\23\22\0\3\23\3\0\4\23\1\0\14\23\1\103"+
    "\2\23\1\104\12\23\22\0\3\23\3\0\4\23\1\0"+
    "\17\23\1\72\12\23\22\0\3\23\3\0\4\23\1\0"+
    "\6\23\1\105\7\23\1\106\13\23\22\0\3\23\3\0"+
    "\4\23\1\0\17\23\1\107\12\23\22\0\3\23\3\0"+
    "\4\23\1\0\5\23\1\110\24\23\22\0\3\23\3\0"+
    "\4\23\1\0\10\23\1\111\1\112\11\23\1\113\2\23"+
    "\1\114\3\23\22\0\3\23\3\0\4\23\1\0\30\23"+
    "\1\115\1\23\22\0\3\23\3\0\4\23\1\0\16\23"+
    "\1\116\13\23\22\0\3\23\3\0\4\23\1\0\17\23"+
    "\1\117\12\23\22\0\3\23\3\0\4\23\1\0\10\23"+
    "\1\120\21\23\26\0\1\12\40\0\1\12\2\44\1\0"+
    "\2\44\1\0\1\44\1\0\23\44\1\0\33\44\7\0"+
    "\1\121\42\0\1\122\2\0\1\123\1\0\1\124\16\0"+
    "\1\125\71\0\1\125\66\0\1\50\20\0\1\50\1\0"+
    "\2\50\2\0\2\50\7\0\1\50\2\0\1\50\1\0"+
    "\1\50\1\0\1\50\4\0\1\50\2\60\4\0\11\60"+
    "\1\61\1\60\3\126\45\60\4\0\11\60\1\61\1\60"+
    "\3\127\43\60\14\130\1\131\52\130\2\57\1\4\2\57"+
    "\1\5\61\57\21\0\3\132\64\0\3\133\62\0\1\125"+
    "\1\0\2\134\1\135\3\0\4\136\1\0\32\136\20\0"+
    "\1\125\1\0\2\137\1\135\3\0\4\136\1\0\32\136"+
    "\22\0\3\140\3\0\4\136\1\0\32\136\22\0\3\141"+
    "\3\0\2\142\2\143\1\0\1\136\6\144\23\145\22\0"+
    "\3\146\3\0\2\147\2\150\2\0\6\151\23\152\1\0"+
    "\2\60\4\0\11\60\1\61\1\60\3\153\3\60\4\64"+
    "\1\60\32\64\3\60\4\0\11\60\1\61\1\60\1\153"+
    "\2\154\3\60\4\71\1\60\1\64\31\71\1\60\21\0"+
    "\3\140\3\0\4\155\1\0\1\136\31\155\22\0\3\23"+
    "\3\0\4\23\1\0\23\23\1\156\6\23\22\0\3\23"+
    "\3\0\4\23\1\0\5\23\1\157\24\23\22\0\3\23"+
    "\3\0\4\23\1\0\22\23\1\160\7\23\22\0\3\23"+
    "\3\0\4\23\1\0\1\23\1\104\30\23\22\0\3\23"+
    "\3\0\4\23\1\0\16\23\1\161\13\23\22\0\3\23"+
    "\3\0\4\23\1\0\6\23\1\162\23\23\22\0\3\23"+
    "\3\0\4\23\1\0\24\23\1\163\5\23\22\0\3\23"+
    "\3\0\4\23\1\0\24\23\1\164\5\23\22\0\3\23"+
    "\3\0\4\23\1\0\23\23\1\165\6\23\22\0\3\23"+
    "\3\0\4\23\1\0\17\23\1\166\12\23\22\0\3\23"+
    "\3\0\4\23\1\0\21\23\1\105\10\23\22\0\3\23"+
    "\3\0\4\23\1\0\23\23\1\105\6\23\22\0\3\23"+
    "\3\0\4\23\1\0\16\23\1\167\13\23\22\0\3\23"+
    "\3\0\4\23\1\0\7\23\1\170\13\23\1\171\6\23"+
    "\22\0\3\23\3\0\4\23\1\0\17\23\1\172\12\23"+
    "\22\0\3\23\3\0\4\23\1\0\7\23\1\173\21\23"+
    "\1\174\22\0\3\23\3\0\4\23\1\0\1\23\1\175"+
    "\17\23\1\176\10\23\22\0\3\23\3\0\4\23\1\0"+
    "\11\23\1\177\20\23\22\0\3\23\3\0\4\23\1\0"+
    "\20\23\1\200\11\23\22\0\3\23\3\0\4\23\1\0"+
    "\11\23\1\201\10\23\1\202\7\23\22\0\3\23\3\0"+
    "\4\23\1\0\11\23\1\203\2\23\1\204\15\23\22\0"+
    "\3\23\3\0\4\23\1\0\11\23\1\205\20\23\20\0"+
    "\1\125\1\0\3\206\43\0\2\60\4\0\11\60\1\61"+
    "\1\60\3\207\43\60\14\130\1\210\66\130\1\210\3\130"+
    "\1\211\46\130\21\0\3\132\4\0\1\212\10\0\1\212"+
    "\46\0\3\133\4\0\1\212\10\0\1\212\44\0\1\125"+
    "\1\0\2\134\1\135\3\0\1\136\1\213\2\136\1\0"+
    "\5\136\1\213\24\136\20\0\1\125\1\0\2\137\1\135"+
    "\3\0\1\136\1\213\2\136\1\0\5\136\1\213\24\136"+
    "\22\0\3\136\3\0\4\136\1\0\32\136\20\0\1\125"+
    "\1\0\2\137\1\214\3\0\1\136\1\213\2\136\1\0"+
    "\5\136\1\213\24\136\22\0\3\140\3\0\1\136\1\213"+
    "\2\136\1\0\5\136\1\213\24\136\22\0\3\141\3\0"+
    "\1\142\1\215\2\136\1\0\1\136\4\144\1\216\1\144"+
    "\23\136\22\0\3\142\3\0\2\142\2\136\1\0\32\136"+
    "\22\0\3\136\3\0\2\136\2\143\1\0\32\136\22\0"+
    "\3\144\3\0\4\136\1\0\1\136\6\144\23\136\22\0"+
    "\3\136\3\0\4\136\1\0\7\136\23\145\22\0\3\146"+
    "\3\0\1\147\1\217\4\0\4\151\1\220\1\151\45\0"+
    "\3\147\3\0\2\147\67\0\2\150\55\0\3\151\11\0"+
    "\6\151\67\0\23\152\1\0\2\60\4\0\11\60\1\61"+
    "\1\60\3\153\3\60\1\64\1\221\2\64\1\60\5\64"+
    "\1\221\24\64\3\60\4\0\11\60\1\61\1\60\1\153"+
    "\2\154\3\60\1\71\1\222\2\71\1\60\1\64\4\71"+
    "\1\222\24\71\1\60\21\0\3\136\3\0\4\155\1\0"+
    "\1\136\31\155\22\0\3\23\3\0\4\23\1\0\17\23"+
    "\1\105\12\23\22\0\3\23\3\0\4\23\1\0\1\23"+
    "\1\223\30\23\22\0\3\23\3\0\4\23\1\0\5\23"+
    "\1\105\24\23\22\0\3\23\3\0\4\23\1\0\22\23"+
    "\1\106\1\224\6\23\22\0\3\23\3\0\4\23\1\0"+
    "\1\23\1\225\30\23\22\0\3\23\3\0\4\23\1\0"+
    "\2\23\1\205\27\23\22\0\3\23\3\0\4\23\1\0"+
    "\15\23\1\105\14\23\22\0\3\23\3\0\4\23\1\0"+
    "\5\23\1\226\24\23\22\0\3\23\3\0\4\23\1\0"+
    "\1\23\1\106\30\23\22\0\3\23\3\0\4\23\1\0"+
    "\7\23\1\105\22\23\22\0\3\23\3\0\4\23\1\0"+
    "\11\23\1\227\20\23\22\0\3\23\3\0\4\23\1\0"+
    "\24\23\1\226\5\23\22\0\3\23\3\0\4\23\1\0"+
    "\21\23\1\106\10\23\22\0\3\23\3\0\4\23\1\0"+
    "\16\23\1\230\13\23\22\0\3\23\3\0\4\23\1\0"+
    "\5\23\1\231\24\23\22\0\3\23\3\0\4\23\1\0"+
    "\23\23\1\232\6\23\22\0\3\23\3\0\4\23\1\0"+
    "\24\23\1\233\5\23\22\0\3\23\3\0\4\23\1\0"+
    "\23\23\1\234\6\23\22\0\3\23\3\0\4\23\1\0"+
    "\5\23\1\235\24\23\22\0\3\23\3\0\4\23\1\0"+
    "\17\23\1\236\12\23\22\0\3\23\3\0\4\23\1\0"+
    "\11\23\1\237\20\23\22\0\3\23\3\0\4\23\1\0"+
    "\4\23\1\105\25\23\22\0\3\23\3\0\4\23\1\0"+
    "\1\23\1\240\30\23\22\0\3\23\3\0\4\23\1\0"+
    "\14\23\1\160\15\23\20\0\1\125\1\0\3\206\4\0"+
    "\1\212\10\0\1\212\25\0\2\60\4\0\11\60\1\61"+
    "\1\60\3\207\4\60\1\241\10\60\1\241\25\60\14\130"+
    "\1\210\3\130\1\4\46\130\15\0\2\52\2\0\3\55"+
    "\60\0\2\52\2\0\3\242\3\0\4\136\1\0\32\136"+
    "\20\0\1\125\1\0\3\214\3\0\1\136\1\213\2\136"+
    "\1\0\5\136\1\213\24\136\16\0\2\52\2\0\3\142"+
    "\3\0\2\142\2\136\1\0\32\136\16\0\2\52\2\0"+
    "\3\144\3\0\4\136\1\0\1\136\6\144\23\136\16\0"+
    "\2\52\2\0\3\147\3\0\2\147\53\0\2\52\2\0"+
    "\3\151\11\0\6\151\41\0\2\52\2\0\3\243\3\0"+
    "\4\136\1\0\32\136\16\0\2\52\2\0\3\243\3\0"+
    "\4\155\1\0\1\136\31\155\22\0\3\23\3\0\4\23"+
    "\1\0\13\23\1\105\16\23\22\0\3\23\3\0\4\23"+
    "\1\0\11\23\1\244\20\23\22\0\3\23\3\0\4\23"+
    "\1\0\24\23\1\245\5\23\22\0\3\23\3\0\4\23"+
    "\1\0\21\23\1\236\10\23\22\0\3\23\3\0\4\23"+
    "\1\0\22\23\1\246\7\23\22\0\3\23\3\0\4\23"+
    "\1\0\5\23\1\203\24\23\22\0\3\23\3\0\4\23"+
    "\1\0\17\23\1\247\12\23\22\0\3\23\3\0\4\23"+
    "\1\0\11\23\1\250\20\23\22\0\3\23\3\0\4\23"+
    "\1\0\3\23\1\106\26\23\22\0\3\23\3\0\4\23"+
    "\1\0\3\23\1\251\26\23\22\0\3\23\3\0\4\23"+
    "\1\0\4\23\1\252\25\23\22\0\3\23\3\0\4\23"+
    "\1\0\16\23\1\105\13\23\22\0\3\23\3\0\4\23"+
    "\1\0\7\23\1\173\22\23\22\0\3\23\3\0\4\23"+
    "\1\0\23\23\1\120\6\23\16\0\2\52\2\0\3\133"+
    "\64\0\3\242\3\0\4\136\1\0\32\136\22\0\3\243"+
    "\3\0\1\136\1\213\2\136\1\0\5\136\1\213\24\136"+
    "\22\0\3\23\3\0\4\23\1\0\16\23\1\253\13\23"+
    "\22\0\3\23\3\0\4\23\1\0\14\23\1\106\15\23"+
    "\22\0\3\23\3\0\4\23\1\0\23\23\1\254\6\23"+
    "\22\0\3\23\3\0\4\23\1\0\6\23\1\105\23\23"+
    "\22\0\3\23\3\0\4\23\1\0\3\23\1\105\26\23"+
    "\22\0\3\23\3\0\4\23\1\0\10\23\1\105\21\23"+
    "\22\0\3\23\3\0\4\23\1\0\5\23\1\247\24\23"+
    "\22\0\3\23\3\0\4\23\1\0\24\23\1\160\5\23"+
    "\22\0\3\23\3\0\4\23\1\0\5\23\1\104\24\23"+
    "\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8800];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\5\1\1\11\32\1\1\11\1\1\6\0"+
    "\1\1\1\0\1\1\1\0\5\1\1\0\32\1\5\11"+
    "\5\0\53\1\3\0\1\1\1\0\26\1\1\0\13\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[172];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
	// string generation with STRING state
	private StringBuffer stringBuilder = new StringBuffer();

	// error lists
	ArrayList<TokenError> errorList = new ArrayList<>();

	public ArrayList<TokenError> getErrorList() {
		ArrayList<TokenError> errorsList = (ArrayList<TokenError>) this.errorList.clone();
		this.errorList.clear();
		return errorsList;
	}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public CLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) throws IllegalTokenException {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new IllegalTokenException(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  throws IllegalTokenException {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException, IllegalTokenException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { this.errorList.add(new TokenError(yyline, yycolumn, yytext(), "Illegal character"));
	throw new IllegalTokenException("Illegal character <" + yytext() + ">" + "[Line:" + yyline + ",Column:" + yycolumn + "]");
            }
            // fall through
          case 19: break;
          case 2:
            { /* do nothing */
            }
            // fall through
          case 20: break;
          case 3:
            { return new OperatorToken(yyline, yycolumn, yytext());
            }
            // fall through
          case 21: break;
          case 4:
            { stringBuilder.setLength(0); yybegin(STRING);
            }
            // fall through
          case 22: break;
          case 5:
            { return new LiteralToken(yyline, yycolumn, yytext());
            }
            // fall through
          case 23: break;
          case 6:
            { return new IdentifierToken(yyline, yycolumn, yytext());
            }
            // fall through
          case 24: break;
          case 7:
            { stringBuilder.append( yytext() );
            }
            // fall through
          case 25: break;
          case 8:
            { yybegin(YYINITIAL);
		return new LiteralToken(yyline, yycolumn, stringBuilder.toString());
            }
            // fall through
          case 26: break;
          case 9:
            { stringBuilder.append('\\');
            }
            // fall through
          case 27: break;
          case 10:
            { this.errorList.add(new TokenError(yyline, yycolumn, yytext(), "Literal octal value must contain [0-7] digits"));
            }
            // fall through
          case 28: break;
          case 11:
            { this.errorList.add(new TokenError(yyline, yycolumn, yytext(), "Identifier cannot start with number(s)"));
            }
            // fall through
          case 29: break;
          case 12:
            { this.errorList.add(new TokenError(yyline, yycolumn, yytext(), "Literal integer value must contain [0-9] digits"));
            }
            // fall through
          case 30: break;
          case 13:
            { return new KeywordToken(yyline, yycolumn, yytext());
            }
            // fall through
          case 31: break;
          case 14:
            { stringBuilder.append('\"');
            }
            // fall through
          case 32: break;
          case 15:
            { stringBuilder.append('\n');
            }
            // fall through
          case 33: break;
          case 16:
            { stringBuilder.append('\r');
            }
            // fall through
          case 34: break;
          case 17:
            { stringBuilder.append('\t');
            }
            // fall through
          case 35: break;
          case 18:
            { this.errorList.add(new TokenError(yyline, yycolumn, yytext(), "Literal hexadecimal value must contain 0-9 or (a-f|A-F) "));
            }
            // fall through
          case 36: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
