
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int KW_DOUBLE = 11;
  public static final int KW_SIZEOF = 25;
  public static final int KW_VOLATILE = 33;
  public static final int OP_MULT = 38;
  public static final int OP_MOD = 39;
  public static final int KW_STRUCT = 27;
  public static final int OP_MINUS = 37;
  public static final int KW_CASE = 5;
  public static final int OP_SHIFTLEFTASSIGN = 64;
  public static final int KW_AUTO = 3;
  public static final int OP_WRAPPERPARENTHESISLEFT = 72;
  public static final int OP_GT = 44;
  public static final int OP_DIV = 35;
  public static final int KW_SHORT = 23;
  public static final int LIT_FLOATVALUE = 83;
  public static final int KW_FOR = 16;
  public static final int OP_LTE = 42;
  public static final int KW_REGISTER = 21;
  public static final int KW_EXTERN = 14;
  public static final int OP_WRAPPERSQUAREPARENTHESISRIGHT = 75;
  public static final int KW_CONST = 7;
  public static final int OP_WRAPPERKEYPARENTHESISRIGHT = 77;
  public static final int KW_INT = 19;
  public static final int OP_POINTEROPERATOR = 79;
  public static final int LIT_DECIMALVALUE = 82;
  public static final int OP_ASIG = 68;
  public static final int LIT_CHARVALUE = 84;
  public static final int KW_ENUM = 13;
  public static final int OP_SHIFTRIGHTASSIGN = 65;
  public static final int KW_SWITCH = 28;
  public static final int OP_WRAPPERPARENTHESISRIGHT = 73;
  public static final int KW_DEFAULT = 9;
  public static final int OP_LT = 43;
  public static final int KW_RETURN = 22;
  public static final int OP_GTE = 41;
  public static final int OP_MINUSMINUSASSIGN = 58;
  public static final int OP_PLUSPLUSASSIGN = 59;
  public static final int OP_PLUSASSIGN = 54;
  public static final int OP_TERNARYOPERATORQUESTIONMARK = 66;
  public static final int KW_FLOAT = 15;
  public static final int KW_GOTO = 17;
  public static final int OP_NOTASSIGN = 62;
  public static final int LIT_STRINGDEF = 86;
  public static final int OP_COMMA = 40;
  public static final int OP_NEGATION = 53;
  public static final int OP_WRAPPERSQUAREPARENTHESISLEFT = 74;
  public static final int EOF = 0;
  public static final int OP_AND = 49;
  public static final int OP_ORCOMP = 46;
  public static final int OP_XOR = 50;
  public static final int OP_TERNARYOPERATIONDOUBLEDOT = 67;
  public static final int OP_POINTEROPERATORASTERISC = 80;
  public static final int KW_DO = 10;
  public static final int OP_MINUSASSIGN = 55;
  public static final int OP_INSTRUCTIONENDOPERATOR = 78;
  public static final int OP_ORASSIGN = 63;
  public static final int LIT_EXPONENTIALDEF = 87;
  public static final int KW_LONG = 20;
  public static final int OP_ANDCOMP = 47;
  public static final int IDENT = 2;
  public static final int error = 1;
  public static final int KW_WHILE = 34;
  public static final int KW_UNION = 30;
  public static final int KW_TYPEDEF = 29;
  public static final int KW_CHAR = 6;
  public static final int OP_DIVASSIGN = 57;
  public static final int OP_MULTASSIGN = 56;
  public static final int KW_VOID = 32;
  public static final int OP_SHIFTOPLEFT = 70;
  public static final int KW_STATIC = 26;
  public static final int KW_ELSE = 12;
  public static final int OP_WRAPPERKEYPARENTHESISLEFT = 76;
  public static final int KW_BREAK = 4;
  public static final int OP_NOTEQUALCOMP = 45;
  public static final int OP_SHIFTOPRIGHT = 69;
  public static final int LIT_OCTALVALUE = 85;
  public static final int KW_SIGNED = 24;
  public static final int OP_EQUALCOMP = 48;
  public static final int OP_ANDASSIGN = 61;
  public static final int KW_IF = 18;
  public static final int KW_CONTINUE = 8;
  public static final int OP_OR = 51;
  public static final int KW_UNSIGNED = 31;
  public static final int LIT_HEXVALUE = 81;
  public static final int OP_PROPOPERATOR = 71;
  public static final int OP_NOT = 52;
  public static final int OP_PLUS = 36;
  public static final int OP_MODASSIGN = 60;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENT",
  "KW_AUTO",
  "KW_BREAK",
  "KW_CASE",
  "KW_CHAR",
  "KW_CONST",
  "KW_CONTINUE",
  "KW_DEFAULT",
  "KW_DO",
  "KW_DOUBLE",
  "KW_ELSE",
  "KW_ENUM",
  "KW_EXTERN",
  "KW_FLOAT",
  "KW_FOR",
  "KW_GOTO",
  "KW_IF",
  "KW_INT",
  "KW_LONG",
  "KW_REGISTER",
  "KW_RETURN",
  "KW_SHORT",
  "KW_SIGNED",
  "KW_SIZEOF",
  "KW_STATIC",
  "KW_STRUCT",
  "KW_SWITCH",
  "KW_TYPEDEF",
  "KW_UNION",
  "KW_UNSIGNED",
  "KW_VOID",
  "KW_VOLATILE",
  "KW_WHILE",
  "OP_DIV",
  "OP_PLUS",
  "OP_MINUS",
  "OP_MULT",
  "OP_MOD",
  "OP_COMMA",
  "OP_GTE",
  "OP_LTE",
  "OP_LT",
  "OP_GT",
  "OP_NOTEQUALCOMP",
  "OP_ORCOMP",
  "OP_ANDCOMP",
  "OP_EQUALCOMP",
  "OP_AND",
  "OP_XOR",
  "OP_OR",
  "OP_NOT",
  "OP_NEGATION",
  "OP_PLUSASSIGN",
  "OP_MINUSASSIGN",
  "OP_MULTASSIGN",
  "OP_DIVASSIGN",
  "OP_MINUSMINUSASSIGN",
  "OP_PLUSPLUSASSIGN",
  "OP_MODASSIGN",
  "OP_ANDASSIGN",
  "OP_NOTASSIGN",
  "OP_ORASSIGN",
  "OP_SHIFTLEFTASSIGN",
  "OP_SHIFTRIGHTASSIGN",
  "OP_TERNARYOPERATORQUESTIONMARK",
  "OP_TERNARYOPERATIONDOUBLEDOT",
  "OP_ASIG",
  "OP_SHIFTOPRIGHT",
  "OP_SHIFTOPLEFT",
  "OP_PROPOPERATOR",
  "OP_WRAPPERPARENTHESISLEFT",
  "OP_WRAPPERPARENTHESISRIGHT",
  "OP_WRAPPERSQUAREPARENTHESISLEFT",
  "OP_WRAPPERSQUAREPARENTHESISRIGHT",
  "OP_WRAPPERKEYPARENTHESISLEFT",
  "OP_WRAPPERKEYPARENTHESISRIGHT",
  "OP_INSTRUCTIONENDOPERATOR",
  "OP_POINTEROPERATOR",
  "OP_POINTEROPERATORASTERISC",
  "LIT_HEXVALUE",
  "LIT_DECIMALVALUE",
  "LIT_FLOATVALUE",
  "LIT_CHARVALUE",
  "LIT_OCTALVALUE",
  "LIT_STRINGDEF",
  "LIT_EXPONENTIALDEF"
  };
}

